### ISSUE TITLE
Not consistent file names between languages

### ISSUE THREAD

**Issue by elgransan** [oqtane/oqtane.translations#11]
When I did Spanish translation I looked up from Portuguese translation and resource file name was like  xxxresource.langcode.resx and I followed that convention.

But now with the new Arabic and Vietnamese languages the resource names are xxxresource.resx (without the langcode)

Recently I installed the ResxExtractor and It generates the files like xxxresource.resx. (without the langcode either) I made a modification to the code, to add the langcode, if you want I do the PR.

Install the language pack to the framework requires xxxresource.langcode.resx I think this is the way to follow, what do you think?

**Comment by hishamco** [comment]
You are right, seems I miss to push some changes accidently
