### ISSUE TITLE
Localization Life Cycle

### ISSUE THREAD

**Issue by sbwalker** [oqtane/oqtane.translations#16]
I think tremendous progress has been made in the localization area for Oqtane. That being said, I feel like we are still lacking some aspects to tie the entire solution together in a way that serves all stakeholders. 

1. Framework - an initial attempt has been made to implement localization throughout the framework. It is possible that there are a few items which have been missed, or even a few scenarios which are not supported currently (which need to be documented somewhere). Going forward we need to ensure that all new features are localizable. 

2. Resource files - need to be maintained by version, as the set of resources are dependent on a specific version of the Oqtane framework. A set of resources should exist for each official release version of the framework from version 2.1.0 forward. 

3. Translators - in order to maintain the resource files we need to try to minimize the effort required by translators. @hishamco has created a tool to automate the extraction of resources from the framework. This tool does not currently handle all scenarios - but it needs to as soon as possible or else people will attempt to maintain resources manually. Since resource files are just text files it should be possible to do a comparison of the resources extracted for the latest version with the resources for the prior version, so that a translator can easily identify the specific modifications required without having to do a full translation for every new release. 

4. Translators - should be able to create a Nuget package which includes the compiled satellite assembly for their culture. This package should be created for each specific framework version and should be made available on nuget.org. Detailed instructions and a template should be created to explain how to create these packages. 

5. Framework - Oqtane should allow non-technical users to install translation packages into Oqtane similar to how Modules or Themes are installed. I will add this capability. 

Comments?

**Comment by leigh-pointer** [comment]
I agree we need a more robust extraction of resource strings.
Also we should think about SharedResources strings.  I have implemented this in my modules and is pretty simple.

**Comment by sbwalker** [comment]
@leigh-pointer are you able to share some details on how you implemented shared resources

**Comment by leigh-pointer** [comment]
@sbwalker I first created a dummy class in the root of client can called it SharedResources.cs
the contents:
```
namespace [Company].[Module].Client
{
    /// <summary>
    /// Dummy class used to collect shared resurce strings for this module
    /// </summary>
    /// <remarks>
    /// This class can be used with IStringLocalizer interface.
    /// </remarks>
    public class SharedResources
	{
	}
}

```

My resx file is called SharedResources.resx and resides under the /Resources folder

in my razor files it is implemented:

```
@using Microsoft.Extensions.Localization
@using [Company].[Module].Client

@inject IStringLocalizer<Index> Localizer
@inject IStringLocalizer<SharedResources> SharedResources

```

**Comment by hishamco** [comment]
I agree that the tool handle almost the localization strings but not all, I'm trying to cover the missing once or the one that are not **static**, I'm glad that we have 6 languages.

Regarding the tool few enhancements need to be made:

1. Complete the extraction for the remaining static resources
2. Support Modules localization strings

About versioning I'm totally agree with @sbwalker that we need target the localization to a specific Oqtane version, also we need to ship a NuGet packages for Oqtane.Translations, this may need a support from @sbwalker or give me some permissions so I can push the packages

**Comment by hishamco** [comment]
> Also we should think about SharedResources strings. I have implemented this in my modules and is pretty simple.

Shared resources are useful in some cases, if there are some places in the Oqtane Framework need to use them, please list them, so we can think about them

**Comment by leigh-pointer** [comment]
@hishamco on first glance I can see the "Cancel" is used 32 times, "Save" 20 times, "Name" 14 and "Loading..."  12

**Comment by hishamco** [comment]
I'm agree that few localized strings could be shared, let us improve the Oqtane resx extractor to extract all static resourses then we could use shared resource if it's possible

**Comment by sbwalker** [comment]
I am trying to understand the expected workflow for the resx extractor tool. I understand that if you are creating a new translation that it will generate the set of resx files for you. And then the you can translate all of the strings. And then a new version of Oqtane is released. If the resx extractor tool is run again, it will generate a new set of resx files - however it will not include any of the earlier work you did to translate the strings. Do we expect translators to re-translate every string for every new release? Do we expect them to use other tools to do a comparison to their prior set of files to manage the differences? This seems very inefficient.

**Comment by hishamco** [comment]
> Do we expect translators to re-translate every string for every new release manually?

Nope

> Do we expect them to use other tools to do a comparison to their prior set of files to manage the differences? If so, what tool?

For now git is the best option to show the diff

> This workflow seems very inefficient. There has to be a way to make it more productive.

Agree, I'm thinking for couple options that I will share ASAP

**Comment by hishamco** [comment]
@sbwalker I pushed some commits to the extraction tool it gets better, furthermore the tool will not overwrite the previous translations if there are

Regrading the workflow as the following:

1. The developer run the `oqtane-extractor` for a newly created language
2. Send the resources keys to the translator
3. In case any update happen with Oqtane version, the developer should run the `oqtane-extractor` again
4. Send the newly added resources to the translator

I think the above workflow is efficient for our case, but I'm thinking to build an online service that will make the workflow much easier and more productive, but still I'm thinking if it will be paid or free service, coz it required a domain and some efforts to develop the platform

**Comment by leigh-pointer** [comment]
No further action
