### ISSUE TITLE
Create NuGet language packs for automatic install/upgrade

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.translations#25]
This is related to #17 and #18, but since it's a separate aspect I wanted to create a new issue.

**Goal**

Create automatic nuget packages for simple install / upgrade from the Oqtane admin-UI. 

**Challanges**

1. Create the packages automatically
2. Deploy them automatically (or ensure someone does this regularly)
3. Ensure that Oqtane installation assistant reliably figures out which package would be the most ideal. See below

**Figuring out the most Ideal Package**

1. List all available languages
2. Prioritize by version...
3. ...but still offer older versions in case there is no latest update (this will happen a lot on less maintained languages packs
3. Allow some kind of sub-version to show newer release without requiring a newer Oqtane. So for Oqtane 2.1.0 the language pack may go through some iterations and have a 2.1.0.1 and a 2.1.0.2 release. So even though the version number is bigger than the current Oqtane, it's still the most appropriate

**Comment by sbwalker** [comment]
@iJungleboy Oqtane 2.1 was already enhanced with the ability to install packaged language packages through the admin UI - it is in the Admin / Languages area. It currently works the same as all other extensibility points in Oqtane where you can either upload a Nuget package or you can download a Nuget package from nuget,org. When downloading from Nuget.org the system displays all packages which have a "oqtane language" tag ( you can see I included the tag in the nuspec I created in the de-DE folder on the weekend ). It currently will display all versions for all languages - and it is up to the user to choose the correct option for their installation. The is also a dependency node in the nuspec which specifies the maximum Oqtane version which the language pack should be installed on.

**Comment by iJungleboy** [comment]
@sbwalker I think for now that's fine. Some day in future this will need to be enhanced, but let's tackle other priorities first ;)
