### ISSUE TITLE
Strange translations in de-DE

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.translations#26]
For all DB config razor files

LocalDBConfig.de-DE.resx(121):<value>@field.HelpText</value>
<value>@field.HelpText</value> 

LocalDBConfig.de-DE.resx(124):<value>@Localizer[$"{field.FriendlyName}:"]</value>
<value>@Localizer[$"{field.FriendlyName}:"]</value>

Not sure how these will get translated?

**Comment by hishamco** [comment]
Does the translation extracted using `Oqtane.ResxExtractor` tool?

**Comment by hishamco** [comment]
Does the translation extracted using `Oqtane.ResxExtractor` tool?

**Comment by hishamco** [comment]
Does the translation extracted using `Oqtane.ResxExtractor` tool?

**Comment by leigh-pointer** [comment]
> Does the translation extracted using `Oqtane.ResxExtractor` tool?

@hishamco no it I found this just looking at the file contents.  @sbwalker fixed up the files

**Comment by leigh-pointer** [comment]
No further action
