### ISSUE TITLE
Add default resources (English)

### ISSUE THREAD

**Issue by hishamco** [oqtane/oqtane.translations#3]
- [x] Add resources that's added via `IStringLocalizer`
- [x] Add resources that's added via `Label` component
- [x] Add resources that's added via `ActionDialog` component
- [x] Add resources that's added via `ActionLink` component
- [x] Add resources that's added via `Section` component
- [x] Add resources that's added via `TabPanel` component

**Comment by hishamco** [comment]
@sbwalker it's done from my side, @chlupac you can start with Czech translations if you want to ;)

**Comment by sbwalker** [comment]
@hishamco would it be possible to include some instruction on the home of this repo the approach that someone would take in order to integrate these language resources into their Oqtane instance?

**Comment by hishamco** [comment]
Sure, that's my next plane, also I will add an Arabic translations in the upcoming days
