### ISSUE TITLE
Write steps to use translations in Oqtane Framework

### ISSUE THREAD

**Issue by hishamco** [oqtane/oqtane.translations#5]

**Comment by sbwalker** [comment]
I dont think full docs are needed - just some basic steps on how people are expected to utilize the RESX files in this repo to localize the framework.

**Comment by hishamco** [comment]
That's what I mean ;)

**Comment by hishamco** [comment]
Fixed in https://github.com/oqtane/oqtane.translations/commit/694f8e637a0df3092937cb4df70b39b8494e4f2f
