### ISSUE TITLE
The doc is not clear

### ISSUE THREAD

**Issue by elgransan** [oqtane/oqtane.translations#7]
Hello I want to translate to spanish but I don't understand how to config the folder inside the project, it says:

`what you need is to copy the translations folder content into Oqtane.Client project more specifically into Resources folder`

But there is no "Resources" folder in Oqtane.Client. There is one in Oqtane.Server and is empty, is that the one? The problem is that because a default language is not installed, I cannot use it as an example either.

**Comment by hishamco** [comment]
Thanks @elgransan, you are right we are working to improve the instructions, but I don't have suitable time to update them

> But there is no "Resources" folder in Oqtane.Client. 

You are right, I will try to push a PR to make this work. For now you can create a `Resources` folder, then your could try a Portuguese language, coz it's the only one pushed, I'm struggling to add an Arabic language too

Thanks

**Comment by hishamco** [comment]
The PR is created https://github.com/oqtane/oqtane.framework/pull/1202

**Comment by elgransan** [comment]
Sorry, I created the "Resource" folder in client project but I' getting an error:

`The satellite assemblies folder named 'Español (es-ES)' is not found.`

![image](https://user-images.githubusercontent.com/9949584/112874572-7b6bf200-9099-11eb-857c-6b07d16269a9.png)

This class is looking for the translation folder in "bin" folder of server project, but is not being copied. I think I'm missing something.

**Comment by hishamco** [comment]
> The satellite assemblies folder named 'Español (es-ES)' is not found.

The name is mentioned just for organizing the resources in the repo, please add its content directly into `Resources` folder

**Comment by elgransan** [comment]
But If I want the software to be multi-language?

**Comment by hishamco** [comment]
Same thing, the suffix of the RESX files should be different such `Index.fr. resx`, `Index.ar.resx`

**Comment by elgransan** [comment]
Sorry, I understood, I could do it, thank you

**Comment by elgransan** [comment]
One last question, can I user generic language "es" instead of "es-ES" or "es-MX" or another? I tried that way and works but I don't know if could fail in some point

**Comment by hishamco** [comment]
Yes you could, but in case you want to use a specific culture you should use `es-ES` or `es-MX`

> I tried that way and works but I don't know if could fail in some point

You should add `es` to supported cultures in `appsettings.json`

**Comment by hishamco** [comment]
@elgransan  I added an Arabic resources for Oqtane Framework also I update `Oqtane.ResxExtractor` now can easily generate your culture specific resources by run the `oqtane-extractor -c={Culture}` command

Hope this help you to generate Spanish resources ;)

**Comment by elgransan** [comment]
Excelent, I uploaded the spanish language support. I saw in some resource files strange translations, feels like a bug (maybe on the ResxExtractor?):

![image](https://user-images.githubusercontent.com/9949584/113025057-dbc46780-915d-11eb-87e6-f86276ee3fae.png)

**Comment by hishamco** [comment]
Ya, I already recognize some issues in 3 files if I'm not wrong, hope to fix them in both `Oqtane Framework` & `Oqtane.ResxExtractor`

**Comment by elgransan** [comment]
Yes, tomorrow I'll take a look on that

**Comment by leigh-pointer** [comment]
No further action
